language: rust
sudo: false
cache:
  cargo
rust:
  - 1.20.0
  - stable
  - beta
  - nightly
before_install:
  - bash ./ci-scripts/rustfmt.sh

script:
  - cargo fmt -- --write-mode diff
matrix:
  allow_failures:
    - rust: nightly
